from fastapi import APIRouter

from app.api.routes import admin, auth, bot_api, bugs, cad_test, competitor_analysis, device_integrations, executions, export, feature_tree, feedback, field_test, final_test, jenkins, learning, overall_test, push, reports, requirements, retest, software, sse, stage5 as overall_test_legacy, task_board, terminals, user_ai_config, users, versions, workbench, zentao_ai, zentao_binding, zentao_bug_actions, zentao_hydrate, zentao_testcases, zentao_version

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(versions.router)
api_router.include_router(software.router)
api_router.include_router(requirements.router)
api_router.include_router(workbench.router)
api_router.include_router(executions.router)
api_router.include_router(bugs.router)
api_router.include_router(admin.router)
api_router.include_router(reports.router)
api_router.include_router(retest.router)
api_router.include_router(overall_test_legacy.router)
api_router.include_router(overall_test.router)
api_router.include_router(push.router)
api_router.include_router(export.router)
api_router.include_router(feedback.router)
api_router.include_router(field_test.router)
api_router.include_router(final_test.router)
api_router.include_router(learning.router)
api_router.include_router(task_board.router)
api_router.include_router(zentao_testcases.router)
api_router.include_router(zentao_binding.router)
api_router.include_router(zentao_hydrate.router)
api_router.include_router(zentao_bug_actions.router)
api_router.include_router(zentao_version.router)
api_router.include_router(zentao_ai.router)
api_router.include_router(user_ai_config.router)
api_router.include_router(jenkins.router)
api_router.include_router(cad_test.router)
api_router.include_router(competitor_analysis.router)
api_router.include_router(terminals.router)
api_router.include_router(device_integrations.router)
api_router.include_router(bot_api.router)
api_router.include_router(feature_tree.router)
api_router.include_router(sse.router)
